language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
  - 'iojs'
  - '0.12'
addons:
  code_climate:
    repo_token: 'y02ea69f85221efd3051a19e882c87cebc07522bf321374186bb6116301569e5e'
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info